acomode unas cosas de header y footer, hice el css de register
CaC-Node2023/challenge_equipo2 pull request #34
Opened 2023-10-22 16:05 UTC by anah028

Creo que un poco mejor se podria ver el header y el footer en index, use de guia un poco los estilos de fede.
En el header no pude hacer que el submenu me aparezca en columna, si alguien me quiere dar una mano genial, solo quedaria eso me parece. 
El footer creo que quedo bien. 
Ya le di los estilos a register en base a lo de naninho, creo que no se pisa con nada, pero chusmeen por las dudas

2023-10-22 16:08 UTC, anah028 commented on css/pages/register.css
> +    border-bottom: solid var(--primary-solid);
Esto quiero que por ahi naninho lo chusmees, porque le borre un cachito de codigo porque no me aparecia la linea en el input, creo que no romperia nada, cualquier cosa avisame y le cambio los nombres a los form de register, como para que queden solo para esta pagina

2023-10-29 17:04 UTC, naninho205 requested changes
Eso es todo, avisame cuando esté y hago el merge.

2023-10-29 17:04 UTC, naninho205 commented on pages/admin/register.html
> +                <button type="submit">Registrarse</button>
Falta darle estilo a este botón.

Creo que se un form__btn btn btn--primary btn--large.

2023-10-29 17:04 UTC, naninho205 commented on pages/admin/register.html
> +                <label for="terminos">Acepto <a href="terminos_y_condiciones.html" target="_blank">Términos y
Y por último, en el FIGMA esta label tiene un tamaño de fuente distinto e incluye un link.

El link puede ser de clase form__link (ya definida).

2023-10-29 18:22 UTC, anah028 commented on css/pages/register.css
> +    border-bottom: solid var(--primary-solid);
Esto ready

2023-10-29 18:22 UTC, anah028 commented on css/partials/header.css
> +    gap: var(--spacing-240);
ready

2023-10-29 18:42 UTC, anah028 commented
Creo que ya acomode todas las correcciones que me hizo naninho

2023-10-29 19:00 UTC, naninho205 approved these changes
Nice.

2023-10-29 19:01 UTC, merged