[SHOP]AGREMO HTML HOME Y CSS CON MODIFICACIONES
CaC-Node2023/challenge_equipo2 pull request #39
Opened 2023-11-07 18:22 UTC by catok2

APLICO MODIFICACIONES EN SHOP.HTML Y SHOP.CSS. RESPECTO A LA VISUAL . VERIFICAR QUE SE VEA BIEN , HEADER, ASIDE, MAIN, FOOTER RESPECTIVAMENTE  AL DISEÑO

2023-11-08 04:12 UTC, naninho205 requested changes
Hola Alan,

Mayormente se ve piola.

Pero estuviste medio gato y no linkeaste las imágenes correctas para que se vea igual que el Figma (son todos Harry Potter, jaj).

Para cerrar la mission 2 tendrían que estar funcionando también las transiciones entre imágenes (al hacer hover). Veo que tu HTML está bien y lo comentaste, así que supongo que se debe a que es responsabilidad de small-card.css.

Creo que a eso lo tenía asignado Sabrina, hablalo con ella de última.

Después, lo que sí no se está mostrando bien es el paginador. Vi que en el HTML está definida la clase "pagination__link", pero no está implementada en el css.

Así que después chequeá eso.

2023-11-14 01:47 UTC, catok2 commented
ahi aplique modificaciones al paginado, y descomente las imagenes comentadas. hice algunos arreglos en los inputs . y aplique un poco de hover .

2023-11-14 19:48 UTC, fedetrip approved these changes

2023-11-14 19:48 UTC, naninho205 approved these changes

2023-11-14 19:51 UTC, merged