sliders de index e item
CaC-Node2023/challenge_equipo2 pull request #47
Opened 2023-11-18 02:46 UTC by anah028

2023-11-18 14:36 UTC, fedetrip approved these changes
lo veo muy bien, vamos que terminamos con la mission 3!!

2023-11-18 14:39 UTC, fedetrip requested changes
esta muy bien pero hay una diferencia con el figma y lo de pablo y es que las flechitas tendrian que estar un poco mas separada de las cards

2023-11-26 13:42 UTC, fedetrip approved these changes

2023-11-26 13:49 UTC, naninho205 approved these changes

2023-11-26 13:49 UTC, merged